---
title: 代码输出——异步任务
date: 2024/9/10
type: frontend
---

[[toc]]

## 第一题

```javascript
const promise1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('success')
  }, 1000)
})
const promise2 = promise1.then(() => {
  throw new Error('error!!!')
})
console.log('promise1', promise1)
console.log('promise2', promise2)
setTimeout(() => {
  console.log('promise1', promise1)
  console.log('promise2', promise2)
}, 2000)
```

<details>
<summary>结果</summary>

无论是在初始化 Promise 对象过程中还是在 then 方法中抛出错误都会使得 Promise 对象的状态为 rejected。

```javascript
promise1 Promise {<pending>}
promise2 Promise {<pending>}

Uncaught (in promise) Error: error!!!
promise1 Promise {<fulfilled>: "success"}
promise2 Promise {<rejected>: Error: error!!}
```

</details>

## 第二题

```javascript
Promise.resolve().then(() => {
  return new Error('error!!!')
}).then(res => {
  console.log("then: ", res)
}).catch(err => {
  console.log("catch: ", err)
})
```

<details>

<summary>结果</summary>

返回任何一个非 Promise 对象都会被包裹成一个 Promise 对象。这里只是返回了一个 Error 对象，并没有通过 throw 抛出错误，故 Promise 的状态仍是 fulfilled。

```javascript
"then: " "Error: error!!!"
```

</details>

## 第三题

```javascript
const promise = Promise.resolve().then(() => {
  return promise;
})
promise.catch(console.err)
```

<details>

<summary>结果</summary>

then 或者 catch 方法返回的值不能是调用该方法的 Promise 对象本身，否则会检测出死循环报错。

```javascript
Uncaught (in promise) TypeError: Chaining cycle detected for promise #<Promise>
```

</details>

## 第四题

```javascript
Promise.resolve(1)
  .then(2)
  .then(Promise.resolve(3))
  .then(console.log)
```

<details>

<summary>结果</summary>

then 或者 catch 方法的参数期望是一个函数，传入非函数值会导致**值透传**。

第一个 then 和第二个 then 中传入的都不是函数，因此发生了透传，将 resolve(1) 的值直接传到最后一个 then 里，故直接打印出 1 。

```javascript
Uncaught (in promise) TypeError: Chaining cycle detected for promise #<Promise>
```

</details>

## 第五题

```javascript
async function async1() {
  console.log("async1 start");
  await async2();
  console.log("async1 end");
  setTimeout(() => {
    console.log('timer1')
  }, 0)
}
async function async2() {
  setTimeout(() => {
    console.log('timer2')
  }, 0)
  console.log("async2");
}
async1();
setTimeout(() => {
  console.log('timer3')
}, 0)
console.log("start")
```

<details>

<summary>结果</summary>

这里的 async2 不需要等待延时器执行完毕，只要返回了便会直接将 await 的后续代码添加进微任务队列中。

```javascript
async1 start
async2
start
async1 end
timer2
timer3
timer1
```

</details>

## 第六题（？）

```javascript
console.log("Start");
async function asyncFunction() {
    console.log("Async 1");
    await new Promise((resolve) => {
        console.log("async await");
        setTimeout(() => {
            console.log("async timeout");
            resolve();
            Promise.resolve().then(() => {
                console.log("promise 1");
            });
        }, 0);
    });
    console.log("Async 2");
}
asyncFunction();
console.log("End");
```

await 关键字属于同步任务，一旦 await 中的 promise 完成兑现或异常时，便会直接将 await 之后的代码添加进微任务队列中。

await 的 promise 在延时器中完成了兑现，会先将 await 之后的代码先添加进微任务队列，再执行 resolve 之后的代码。

```javascript
Start
Async 1
async await
End
async timeout
Async2
promise 1
```

（真的是这样吗？）再来看看后面几个输出结果问题。

------

在原来的基础上，此时在 await 的 promise 执行一个 then 方法时，整个行为却与之前不同。

```javascript
console.log("Start");
asyncFunction();
async function asyncFunction() {
    console.log("Async 1");
    await new Promise((resolve) => {
        console.log("async await");
        setTimeout(() => {
            console.log("async timeout");
            resolve("resolve");
            Promise.resolve().then(() => {
                console.log("promise 1");
            });
        }, 0);
    }).then((res) => console.log(res));
    console.log("Async 2");
}
console.log("End");
```

这里输出 resolve 的结果后，此时发现却是先输出 `promise 1`，随后输出 `Async 2`。

```javascript
Start
Async 1
async await
End
async timeout
resolve
promise 1
Async 2
```

------

如果此时把延时器去掉，行为又发生了变化。

```javascript
console.log("Start");
asyncFunction();
async function asyncFunction() {
    console.log("Async 1");
    await new Promise((resolve) => {
        console.log("async await");
        resolve("resolve");
        Promise.resolve().then(() => {
            console.log("promise 1");
        });
    }).then((res) => console.log(res));
    console.log("Async 2");
}
console.log("End");
```

此时却是先输出 `promise 1`，然后才是输出 resolve 的结果，最后输出 `Async 2`。

```javascript
Start
Async 1
async await
End
promise 1
resolve
Async 2
```

------

此时再把 then 方法去掉，与第一次相比，相当于在第一次的基础上把延时器删除，但输出结果却又不在预期。

```javascript
console.log("Start");
asyncFunction();
async function asyncFunction() {
    console.log("Async 1");
    await new Promise((resolve) => {
        console.log("async await");
        resolve("resolve");
        Promise.resolve().then(() => {
            console.log("promise 1");
        });
    });
    console.log("Async 2");
}
console.log("End");
```

与第一次对照，此时却是先输出 `promise 1`，后输出 `Async 2`。

```javascript
Start
Async 1
async await
End
promise 1
Async 2
```

并不清楚这几种情况的实际运行机制，感觉怎么想逻辑都不太讲得通，此时的运行机制有点混乱。